import { useState, useMemo, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Search, Filter, ArrowUpRight, Loader2 } from 'lucide-react';
import { mockRealities } from '../lib/mockData';
import { cn } from '../lib/utils';
import { motion } from 'motion/react';
import { dbService } from '../services/db';
import { Reality } from '../types';

const categories = ['All', 'Newest', 'Technology', 'History', 'Society', 'Space', 'Business'];

export function Explore() {
  const [activeCategory, setActiveCategory] = useState('All');
  const [searchQuery, setSearchQuery] = useState('');
  const [publicRealities, setPublicRealities] = useState<Reality[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadPublic() {
      setLoading(true);
      try {
        const cloudPublic = await dbService.getPublicRealities(50);
        setPublicRealities(cloudPublic);
      } catch (err) {
        console.error('Failed to load public realities', err);
      } finally {
        setLoading(false);
      }
    }
    loadPublic();
  }, []);

  const allRealities = useMemo(() => {
    const mockMap = new Map(mockRealities.map(r => [r.id, r]));
    const localMap = new Map(publicRealities.map(r => [r.id, r]));
    const combined = Array.from(new Map([...mockMap, ...localMap]).values());
    return combined;
  }, [publicRealities]);

  const filteredRealities = allRealities.filter(reality => {
    const matchesSearch = reality.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
                          reality.summary.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesCategory = activeCategory === 'All' || 
                            
                            reality.categories.includes(activeCategory as any);
    return matchesSearch && matchesCategory;
  });
  if (activeCategory === 'Newest') {
    filteredRealities.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  }

  return (
    <div className="w-full flex-1 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-12">
        <div>
          <h1 className="text-3xl md:text-4xl font-medium tracking-tight text-[var(--color-text-primary)] mb-3">
            Explore Realities
          </h1>
          <p className="text-[var(--color-text-secondary)] font-light">
            Discover alternate timelines generated by the community.
          </p>
        </div>
        
        <div className="flex items-center gap-3 w-full md:w-auto">
          <div className="relative flex-1 md:w-64">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[var(--color-text-tertiary)]" />
            <input 
              type="text" 
              placeholder="Search realities..." 
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-4 py-2 bg-[var(--color-surface-primary)] border border-[var(--color-border-subtle)] rounded-full text-sm text-[var(--color-text-primary)] focus:outline-none focus:border-[var(--color-border-focus)] transition-colors"
            />
          </div>
          <button disabled title="Filter options coming soon" className="p-2.5 rounded-full border border-[var(--color-border-subtle)] bg-[var(--color-surface-primary)] text-[var(--color-text-secondary)] opacity-50 cursor-not-allowed transition-colors">
            <Filter className="w-4 h-4" />
          </button>
        </div>
      </div>

      <div className="flex overflow-x-auto pb-4 mb-8 gap-2 no-scrollbar border-b border-[var(--color-border-subtle)]">
        {categories.map(cat => (
          <button
            key={cat}
            onClick={() => setActiveCategory(cat)}
            className={cn(
              "whitespace-nowrap px-4 py-2 rounded-full text-sm font-medium transition-all",
              activeCategory === cat 
                ? "bg-[var(--color-text-primary)] text-[var(--color-background-primary)]" 
                : "text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] hover:bg-[var(--color-surface-secondary)]"
            )}
          >
            {cat}
          </button>
        ))}
      </div>

      {loading ? (
        <div className="py-24 flex justify-center">
          <Loader2 className="w-8 h-8 animate-spin text-[var(--color-text-secondary)]" />
        </div>
      ) : filteredRealities.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredRealities.map((reality, i) => (
            <motion.div
              key={reality.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.1 }}
            >
              <Link 
                to={`/reality/${reality.id}`} 
                className="group flex flex-col h-full bg-[var(--color-surface-primary)] border border-[var(--color-border-subtle)] rounded-2xl overflow-hidden hover:border-[var(--color-border-focus)] transition-all duration-300"
              >
                <div className="p-6 flex flex-col flex-1 relative">
                  <div className="flex items-center gap-2 mb-4">
                    {reality.categories.slice(0, 2).map(cat => (
                      <span key={cat} className="text-[10px] font-semibold tracking-wider uppercase text-[var(--color-text-secondary)] bg-[var(--color-surface-secondary)] px-2 py-1 rounded-sm">
                        {cat}
                      </span>
                    ))}
                  </div>
                  
                  <h3 className="text-xl font-medium text-[var(--color-text-primary)] leading-tight mb-3 pr-6 group-hover:text-[var(--color-accent-tertiary)] transition-colors">
                    {reality.title}
                  </h3>
                  
                  <p className="text-sm text-[var(--color-text-secondary)] line-clamp-3 font-light mt-auto">
                    {reality.summary}
                  </p>

                  <div className="absolute top-6 right-6 opacity-0 group-hover:opacity-100 transition-opacity text-[var(--color-text-secondary)] group-hover:text-[var(--color-text-primary)]">
                    <ArrowUpRight className="w-5 h-5" />
                  </div>
                </div>
                <div className="px-6 py-3 border-t border-[var(--color-border-subtle)] bg-[var(--color-surface-secondary)]/30 flex items-center justify-between text-xs font-medium text-[var(--color-text-tertiary)]">
                  <span>{(reality.views / 1000).toFixed(1)}k views</span>
                  <span>{reality.forkCount} forks</span>
                </div>
              </Link>
            </motion.div>
          ))}
        </div>
      ) : (
        <div className="py-24 text-center flex flex-col items-center">
           <div className="w-16 h-16 rounded-full bg-[var(--color-surface-secondary)] flex items-center justify-center mb-4">
              <Search className="w-6 h-6 text-[var(--color-text-tertiary)]" />
           </div>
           <h3 className="text-lg font-medium text-[var(--color-text-primary)] mb-2">No realities found</h3>
           <p className="text-[var(--color-text-secondary)] font-light max-w-sm">
             We couldn't find any realities matching your current filters. Try adjusting your search or category.
           </p>
        </div>
      )}
    </div>
  );
}
